(function() {
    "use strict";
    var DAY_MS = 24 * 60 * 60 * 1000;
    var REVISIT_DELAY_MS = 7 * DAY_MS;
    var BASE_RADIUS_M = 40;
    var ABSOLUTE_MAX_RADIUS_M = 100;
    var DB_NAME = "giloa-time-trace";
    var DB_VERSION = 1;
    var STORE = "series";
    var dbPromise = null;
    var seriesCache = [];
    var activeSeries = null;
    var pendingCapture = null;
    var pendingResult = null;
    var cameraStream = null;
    var objectUrls = [];
    var prompted = {};

    var TEXT = {
        ko:{title:"시간의 흔적",subtitle:"같은 장소의 변화를 사진으로 이어 보세요.",empty:"아직 시간의 흔적이 없어요. 위치가 있는 사진을 남기면 시작됩니다.",waiting:"재방문까지 기다리는 중",available:"다시 촬영 가능",completed:"회 기록",revisit:"다시 찍기",compare:"비교 보기",traceDate:"{date}부터 가능",remember1:"어? 여기 기억나?",remember2:"일주일 전에 이곳에서 사진을 남겼어.",remember3:"지금의 모습은 얼마나 달라졌을까?",remember4:"같은 구도로 다시 찍어볼래?",later:"나중에",retake:"다시 찍기",outline:"윤곽을 맞춰보세요",opacity:"과거 사진 투명도",external:"휴대전화 카메라 사용",far:"원래 촬영 장소에서 100m 이내로 이동해 주세요.",cameraFail:"카메라 미리보기를 열 수 없어요. 휴대전화 카메라를 사용할 수 있습니다.",almost:"거의 같은 자리예요!",good:"좋아요! 비슷한 구도예요.",adjust:"조금 더 과거 사진에 맞춰볼까요?",different:"방향이나 위치가 많이 달라 보여요.",accept:"이 사진으로 기록하기",before:"일주일 전",now:"지금",turnRight:"조금 오른쪽으로 돌아보세요.",turnLeft:"조금 왼쪽으로 돌아보세요."},
        en:{title:"Time Trace",subtitle:"Revisit a place and photograph how it changes.",empty:"No Time Traces yet. Save a photo with a location to begin.",waiting:"Waiting for revisit",available:"Ready to revisit",completed:"captures",revisit:"Retake",compare:"Compare",traceDate:"Available from {date}",remember1:"Hey, remember this place?",remember2:"You left a photo here a week ago.",remember3:"How much has it changed?",remember4:"Want to retake it from the same angle?",later:"Later",retake:"Retake",outline:"Match the outlines",opacity:"Past photo opacity",external:"Use phone camera",far:"Move within 100 m of the original location.",cameraFail:"The live preview is unavailable. You can use the phone camera.",almost:"Almost the exact same spot!",good:"Great! A similar composition.",adjust:"Try matching the past photo a little more.",different:"The direction or position looks quite different.",accept:"Use this photo",before:"A week ago",now:"Now",turnRight:"Turn slightly to the right.",turnLeft:"Turn slightly to the left."},
        ja:{title:"時間の痕跡",subtitle:"同じ場所の変化を写真でつなげよう。",empty:"時間の痕跡はまだありません。位置付き写真を残すと始まります。",waiting:"再訪待ち",available:"再撮影できます",completed:"回記録",revisit:"もう一度撮る",compare:"比較する",traceDate:"{date}から可能",remember1:"あれ？ここを覚えてる？",remember2:"一週間前にここで写真を残したよ。",remember3:"今はどれくらい変わったかな？",remember4:"同じ構図でもう一度撮ってみる？",later:"あとで",retake:"もう一度撮る",outline:"輪郭を合わせてください",opacity:"過去写真の透明度",external:"端末のカメラを使う",far:"元の撮影場所から100m以内に移動してください。",cameraFail:"カメラプレビューを開けません。端末のカメラを使用できます。",almost:"ほぼ同じ場所です！",good:"いいね！似た構図です。",adjust:"もう少し過去の写真に合わせてみよう。",different:"向きや位置がかなり違うようです。",accept:"この写真で記録",before:"一週間前",now:"今",turnRight:"少し右を向いてください。",turnLeft:"少し左を向いてください。"},
        zh:{title:"时间痕迹",subtitle:"用照片记录同一地点随时间的变化。",empty:"还没有时间痕迹。保存带位置的照片即可开始。",waiting:"等待再次到访",available:"可以再次拍摄",completed:"次记录",revisit:"再次拍摄",compare:"对比查看",traceDate:"{date}起可用",remember1:"咦，还记得这里吗？",remember2:"一周前你在这里留下了一张照片。",remember3:"现在变了多少呢？",remember4:"要用相同构图再拍一次吗？",later:"以后再说",retake:"再次拍摄",outline:"请对齐轮廓",opacity:"旧照片透明度",external:"使用手机相机",far:"请移动到原拍摄地点100米以内。",cameraFail:"无法打开相机预览，可以使用手机相机。",almost:"几乎是同一个位置！",good:"很好，构图很相似。",adjust:"再试着对齐旧照片吧。",different:"方向或位置看起来差别较大。",accept:"使用这张照片记录",before:"一周前",now:"现在",turnRight:"请稍微向右转。",turnLeft:"请稍微向左转。"}
    };
    function lang() { var value = String(typeof currentLang === "string" ? currentLang : document.documentElement.lang || "ko").toLowerCase().split("-")[0]; return TEXT[value] ? value : "en"; }
    function t(key, values) { var value = TEXT[lang()][key] || TEXT.en[key] || key; Object.keys(values || {}).forEach(function(k) { value = value.replace("{" + k + "}", values[k]); }); return value; }
    function uid() { return "trace:" + Date.now().toString(36) + ":" + Math.random().toString(36).slice(2, 9); }
    function openDb() { if (dbPromise) return dbPromise; dbPromise = new Promise(function(resolve, reject) { var request = indexedDB.open(DB_NAME, DB_VERSION); request.onupgradeneeded = function(event) { var db = event.target.result; if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE, { keyPath:"seriesId" }); }; request.onsuccess = function(event) { resolve(event.target.result); }; request.onerror = function(event) { reject(event.target.error); }; }); return dbPromise; }
    function allSeries() { return openDb().then(function(db) { return new Promise(function(resolve, reject) { var request = db.transaction(STORE, "readonly").objectStore(STORE).getAll(); request.onsuccess = function() { seriesCache = request.result || []; resolve(seriesCache); }; request.onerror = function() { reject(request.error); }; }); }); }
    function putSeries(series) { return openDb().then(function(db) { return new Promise(function(resolve, reject) { var tx = db.transaction(STORE, "readwrite"); tx.objectStore(STORE).put(series); tx.oncomplete = function() { var index = seriesCache.findIndex(function(item) { return item.seriesId === series.seriesId; }); if (index >= 0) seriesCache[index] = series; else seriesCache.push(series); resolve(series); }; tx.onerror = function() { reject(tx.error); }; }); }); }
    function deleteSeries(id) { return openDb().then(function(db) { return new Promise(function(resolve) { var tx = db.transaction(STORE, "readwrite"); tx.objectStore(STORE).delete(id); tx.oncomplete = tx.onerror = function() { seriesCache = seriesCache.filter(function(item) { return item.seriesId !== id; }); resolve(); }; }); }); }
    function validLocation(photo) { return photo && isFinite(photo.lat) && isFinite(photo.lng) && Math.abs(Number(photo.lat)) <= 90 && Math.abs(Number(photo.lng)) <= 180 && !(Number(photo.lat) === 0 && Number(photo.lng) === 0); }
    function registerPhoto(photo) { if (!photo || !photo.id || !validLocation(photo)) return Promise.resolve(null); return allSeries().then(function(list) { if (list.some(function(item) { return item.photoIds && item.photoIds.indexOf(photo.id) >= 0; })) return null; var takenAt = Number(photo.time) || Date.now(); return putSeries({ seriesId:uid(), originalPhotoId:photo.id, photoIds:[photo.id], lat:Number(photo.lat), lng:Number(photo.lng), createdAt:takenAt, revisitAvailableAt:takenAt + REVISIT_DELAY_MS, completedCount:0, lastCompletedAt:null, heading:isFinite(photo.heading) ? Number(photo.heading) : null, status:"waiting" }); }); }
    function distanceMeters(aLat, aLng, bLat, bLng) { var rad = Math.PI / 180, dLat=(bLat-aLat)*rad, dLng=(bLng-aLng)*rad, h=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(aLat*rad)*Math.cos(bLat*rad)*Math.sin(dLng/2)*Math.sin(dLng/2); return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)); }
    function radiusForAccuracy(accuracy) { return Math.min(ABSOLUTE_MAX_RADIUS_M, BASE_RADIUS_M + Math.min(60, Math.max(0, Number(accuracy) || 0)) * .75); }
    function proximity(series, position) { if (!series || !position || !validLocation(position)) return { eligible:false, distance:Infinity, radius:BASE_RADIUS_M }; var distance=distanceMeters(series.lat,series.lng,Number(position.lat),Number(position.lng)), radius=radiusForAccuracy(position.accuracy); return { eligible:Date.now() >= Number(series.revisitAvailableAt) && distance <= radius && distance < ABSOLUTE_MAX_RADIUS_M, distance:distance, radius:radius }; }
    function findPhoto(id) { return Array.isArray(window.photos) ? window.photos.find(function(photo) { return photo.id === id; }) : (typeof photos !== "undefined" && Array.isArray(photos) ? photos.find(function(photo) { return photo.id === id; }) : null); }
    function photoSource(id) { var photo=findPhoto(id); if (photo && (photo.photo || photo.thumb || photo.remotePhotoUrl)) return Promise.resolve(photo.photo || photo.thumb || photo.remotePhotoUrl); if (typeof idbGetPhoto !== "function") return Promise.resolve(""); return idbGetPhoto(id).then(function(row) { if (!row) return ""; if (row.originalBlob) { var url=URL.createObjectURL(row.originalBlob); objectUrls.push(url); return url; } return row.photo || row.thumb || ""; }).catch(function() { return ""; }); }
    function releaseMedia() { if (cameraStream) cameraStream.getTracks().forEach(function(track) { track.stop(); }); cameraStream=null; var video=document.getElementById("time-trace-video"); if (video) { video.pause(); video.srcObject=null; } while(objectUrls.length) URL.revokeObjectURL(objectUrls.pop()); }
    function setOpen(id, open) { var node=document.getElementById(id); if (!node) return; node.classList.toggle("open", !!open); node.setAttribute("aria-hidden", open ? "false" : "true"); }
    function formatDate(ms) { try { return new Date(ms).toLocaleDateString(lang()==="ko"?"ko-KR":lang()==="ja"?"ja-JP":lang()==="zh"?"zh-CN":"en-US",{year:"numeric",month:"short",day:"numeric"}); } catch (_) { return ""; } }
    function refreshText() { ["time-trace-title","time-trace-compare-title"].forEach(function(id){var n=document.getElementById(id);if(n)n.textContent=t("title");}); var map={"time-trace-subtitle":"subtitle","time-trace-camera-title":"outline","time-trace-opacity-label":"opacity","time-trace-capture":"retake","time-trace-external-camera":"external","time-trace-retry":"retake","time-trace-accept":"accept","time-trace-before-label":"before","time-trace-after-label":"now","time-trace-menu-label":"title"}; Object.keys(map).forEach(function(id){var n=document.getElementById(id);if(n)n.textContent=t(map[id]);}); }
    function openLibrary() { refreshText(); allSeries().then(renderLibrary).catch(function(error) { console.warn("Time Trace load failed", error); renderLibrary([]); }); setOpen("time-trace-panel",true); }
    function renderLibrary(list) { var root=document.getElementById("time-trace-list"); if(!root)return; root.textContent=""; if(!list.length){var empty=document.createElement("div");empty.className="time-trace-empty";empty.textContent=t("empty");root.appendChild(empty);return;} list.slice().sort(function(a,b){return b.createdAt-a.createdAt;}).forEach(function(series){var item=document.createElement("article");item.className="time-trace-item";var img=document.createElement("img");img.alt="";photoSource(series.photoIds[series.photoIds.length-1]).then(function(src){img.src=src;});var body=document.createElement("div"),title=document.createElement("h3"),copy=document.createElement("p"),status=document.createElement("span"),button=document.createElement("button");title.textContent=formatDate(series.createdAt);var ready=Date.now()>=series.revisitAvailableAt;copy.textContent=ready?t("available"):t("traceDate",{date:formatDate(series.revisitAvailableAt)});status.className="time-trace-status";status.textContent=series.completedCount?series.completedCount+" "+t("completed"):(ready?t("available"):t("waiting"));button.textContent=series.completedCount?t("compare"):t("revisit");button.className="primary";button.disabled=!ready;button.addEventListener("click",function(){setOpen("time-trace-panel",false);series.completedCount?openCompare(series):beginRevisit(series);});body.append(title,copy,status,document.createElement("br"),button);item.append(img,body);root.appendChild(item);}); }
    function currentSnapshot() { if (typeof snapshotCurrentPhotoLocation === "function") { var snap=snapshotCurrentPhotoLocation(); if(snap)return snap; } if (typeof currentPos !== "undefined" && currentPos) return {lat:currentPos.lat,lng:currentPos.lng,accuracy:typeof currentAccuracy!=="undefined"?currentAccuracy:null}; return null; }
    function headingDifference(a,b) { if(!isFinite(a)||!isFinite(b))return null; var diff=((Number(b)-Number(a)+540)%360)-180;return diff; }
    function headingHint(series) { var diff=headingDifference(series.heading,typeof playerHeading!=="undefined"?playerHeading:null); if(diff===null||Math.abs(diff)<25)return "";return diff>0?t("turnLeft"):t("turnRight"); }
    function beginRevisit(series) { var near=proximity(series,currentSnapshot()); if(!near.eligible){alert(t("far"));return;} activeSeries=series; openGuide(series); }
    function openGuide(series) { refreshText(); setOpen("time-trace-camera",true); var overlay=document.getElementById("time-trace-overlay"),fallback=document.getElementById("time-trace-camera-fallback"),video=document.getElementById("time-trace-video"); document.getElementById("time-trace-heading-hint").textContent=headingHint(series); photoSource(series.photoIds[series.photoIds.length-1]).then(function(src){overlay.src=src;}); fallback.style.display="none"; if(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia){navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:960}},audio:false}).then(function(stream){cameraStream=stream;video.srcObject=stream;return video.play();}).catch(function(){fallback.textContent=t("cameraFail");fallback.style.display="grid";});}else{fallback.textContent=t("cameraFail");fallback.style.display="grid";} }
    function closeGuide() { setOpen("time-trace-camera",false); releaseMedia(); }
    function externalCamera() { if(!activeSeries)return; pendingCapture={seriesId:activeSeries.seriesId,startedAt:Date.now()}; closeGuide(); if(typeof triggerCamera==="function")triggerCamera(); }
    function canvasBlob(canvas) { return new Promise(function(resolve){canvas.toBlob(function(blob){resolve(blob);},"image/jpeg",.9);}); }
    function imageFromBlob(blob) { return new Promise(function(resolve,reject){var url=URL.createObjectURL(blob),img=new Image();img.onload=function(){URL.revokeObjectURL(url);resolve(img);};img.onerror=function(){URL.revokeObjectURL(url);reject(new Error("Captured image decode failed"));};img.src=url;}); }
    async function captureFrame() { if(!activeSeries)return; var position=currentSnapshot(),near=proximity(activeSeries,position); if(!near.eligible){alert(t("far"));return;} var video=document.getElementById("time-trace-video"); if(!video||!video.videoWidth){externalCamera();return;} var scale=Math.min(1,1080/video.videoWidth),canvas=document.createElement("canvas");canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext("2d").drawImage(video,0,0,canvas.width,canvas.height);var blob=await canvasBlob(canvas);canvas.width=canvas.height=0;var img=await imageFromBlob(blob);pendingCapture={seriesId:activeSeries.seriesId,startedAt:Date.now()};closeGuide();await processPhoto(img,new Date(),position.lat,position.lng,{originalBlob:blob,sourceType:"camera",locationSource:"current",locationAccuracy:position.accuracy,heading:typeof playerHeading!=="undefined"?playerHeading:null}); }
    function loadImage(src) { return new Promise(function(resolve,reject){var image=new Image();image.onload=function(){resolve(image);};image.onerror=reject;image.src=src;}); }
    function edgeDescriptor(image) { var size=256,canvas=document.createElement("canvas");canvas.width=canvas.height=size;var ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.drawImage(image,0,0,size,size);var pixels=ctx.getImageData(0,0,size,size).data,gray=new Float32Array(size*size),descriptor=new Float32Array(128);for(var i=0;i<gray.length;i++)gray[i]=pixels[i*4]*.299+pixels[i*4+1]*.587+pixels[i*4+2]*.114;for(var y=1;y<size-1;y+=2){for(var x=1;x<size-1;x+=2){var gx=gray[y*size+x+1]-gray[y*size+x-1],gy=gray[(y+1)*size+x]-gray[(y-1)*size+x],mag=Math.sqrt(gx*gx+gy*gy);if(mag<22)continue;var angle=(Math.atan2(gy,gx)+Math.PI)/(2*Math.PI),bin=Math.min(7,Math.floor(angle*8)),cellX=Math.min(3,Math.floor(x/(size/4))),cellY=Math.min(3,Math.floor(y/(size/4)));descriptor[(cellY*4+cellX)*8+bin]+=mag;}}var norm=0;for(var d=0;d<descriptor.length;d++)norm+=descriptor[d]*descriptor[d];norm=Math.sqrt(norm)||1;for(var n=0;n<descriptor.length;n++)descriptor[n]/=norm;canvas.width=canvas.height=0;return descriptor; }
    function cosine(a,b){var sum=0;for(var i=0;i<a.length;i++)sum+=a[i]*b[i];return Math.max(0,Math.min(1,sum));}
    async function imageScore(oldId,newId){var sources=await Promise.all([photoSource(oldId),photoSource(newId)]),images=await Promise.all(sources.map(loadImage));var score=Math.round(cosine(edgeDescriptor(images[0]),edgeDescriptor(images[1]))*100);images.length=0;return score;}
    function combinedScore(series,photo,imgScore){var dist=distanceMeters(series.lat,series.lng,photo.lat,photo.lng),locationScore=Math.max(0,100-dist),headingDiff=headingDifference(series.heading,photo.heading),headingScore=headingDiff===null?null:Math.max(0,100-Math.abs(headingDiff)/1.8),score=headingScore===null?locationScore*.294117+imgScore*.705883:locationScore*.25+headingScore*.15+imgScore*.60;return {finalScore:Math.round(score),locationScore:Math.round(locationScore),headingScore:headingScore===null?null:Math.round(headingScore),imageScore:imgScore,distance:dist};}
    async function prepareResult(series,photo){if(!validLocation(photo)||distanceMeters(series.lat,series.lng,photo.lat,photo.lng)>=ABSOLUTE_MAX_RADIUS_M){pendingResult=null;alert(t("far"));return;}var structural=await imageScore(series.photoIds[series.photoIds.length-1],photo.id).catch(function(){return 50;}),scores=combinedScore(series,photo,structural);pendingResult={series:series,photo:photo,scores:scores};document.getElementById("time-trace-score").textContent=scores.finalScore+" / 100";var key=scores.finalScore>=80?"almost":scores.finalScore>=60?"good":scores.finalScore>=40?"adjust":"different";document.getElementById("time-trace-result-title").textContent=t("title");document.getElementById("time-trace-score-copy").textContent=t(key)+(scores.headingScore!==null&&scores.headingScore<55?" "+headingHint(series):"");setOpen("time-trace-result",true);}
    function acceptResult(){if(!pendingResult)return;var result=pendingResult,series=result.series,photo=result.photo;series.photoIds=series.photoIds.concat([photo.id]);series.completedCount=Number(series.completedCount||0)+1;series.lastCompletedAt=Number(photo.time)||Date.now();series.revisitAvailableAt=series.lastCompletedAt+REVISIT_DELAY_MS;series.heading=isFinite(photo.heading)?Number(photo.heading):series.heading;series.status="waiting";putSeries(series).then(function(){setOpen("time-trace-result",false);pendingResult=null;openCompare(series);});}
    function retryResult(){var series=pendingResult&&pendingResult.series;setOpen("time-trace-result",false);pendingResult=null;if(series)beginRevisit(series);}
    function openCompare(series){refreshText();var ids=series.photoIds;if(ids.length<2)return;Promise.all([photoSource(ids[ids.length-2]),photoSource(ids[ids.length-1])]).then(function(src){document.getElementById("time-trace-before").src=src[0];document.getElementById("time-trace-after").src=src[1];});document.getElementById("time-trace-timeline").textContent=ids.map(function(id){var p=findPhoto(id);return p?formatDate(p.time):"•";}).join(" → ");setOpen("time-trace-compare",true);}
    function checkRevisit(position){allSeries().then(function(list){var match=list.find(function(series){return !prompted[series.seriesId]&&proximity(series,position).eligible;});if(!match)return;prompted[match.seriesId]=true;activeSeries=match;if(typeof showGiloDialogue==="function")showGiloDialogue({name:"Gilo",pages:[t("remember1"),t("remember2"),t("remember3"),t("remember4")],finalLabel:{ko:TEXT.ko.retake,en:TEXT.en.retake,ja:TEXT.ja.retake,zh:TEXT.zh.retake},closeLabel:{ko:TEXT.ko.later,en:TEXT.en.later,ja:TEXT.ja.later,zh:TEXT.zh.later},onComplete:function(){beginRevisit(match);}});}).catch(function(error){console.warn("Time Trace revisit check failed",error);});}
    function onPhotoSaved(event){try{var photo=event.detail&&event.detail.photo;if(!photo)return;if(pendingCapture&&Date.now()-Number(pendingCapture.startedAt||0)<=10*60*1000){var id=pendingCapture.seriesId;pendingCapture=null;allSeries().then(function(list){var series=list.find(function(item){return item.seriesId===id;});if(series)prepareResult(series,photo);});return;}pendingCapture=null;registerPhoto(photo).catch(function(error){console.warn("Time Trace register failed",error);});}catch(error){console.warn("Time Trace photo event failed",error);}}
    function onPhotoDeleted(event){var id=event.detail&&event.detail.photoId;if(!id)return;allSeries().then(function(list){list.forEach(function(series){if(series.originalPhotoId===id){deleteSeries(series.seriesId);return;}if(series.photoIds&&series.photoIds.indexOf(id)>=0){series.photoIds=series.photoIds.filter(function(photoId){return photoId!==id;});series.completedCount=Math.max(0,series.photoIds.length-1);putSeries(series);}});});}
    function bind(){refreshText();document.querySelectorAll("[data-time-trace-close]").forEach(function(node){node.addEventListener("click",function(){setOpen("time-trace-panel",false);releaseMedia();});});document.querySelectorAll("[data-time-trace-camera-close]").forEach(function(node){node.addEventListener("click",closeGuide);});document.querySelectorAll("[data-time-trace-result-close]").forEach(function(node){node.addEventListener("click",function(){setOpen("time-trace-result",false);pendingResult=null;});});document.querySelectorAll("[data-time-trace-compare-close]").forEach(function(node){node.addEventListener("click",function(){setOpen("time-trace-compare",false);releaseMedia();});});document.getElementById("time-trace-opacity").addEventListener("input",function(){document.getElementById("time-trace-overlay").style.opacity=String(Number(this.value)/100);});document.getElementById("time-trace-capture").addEventListener("click",function(){captureFrame().catch(function(error){console.warn("Time Trace capture failed",error);});});document.getElementById("time-trace-external-camera").addEventListener("click",externalCamera);document.getElementById("time-trace-retry").addEventListener("click",retryResult);document.getElementById("time-trace-accept").addEventListener("click",acceptResult);document.getElementById("time-trace-compare-slider").addEventListener("input",function(){document.getElementById("time-trace-after-wrap").style.width=this.value+"%";});window.addEventListener("giloa:photo-saved",onPhotoSaved);window.addEventListener("giloa:photo-deleted",onPhotoDeleted);window.addEventListener("giloa:location-ready",function(event){var detail=event.detail||{};checkRevisit({lat:detail.lat,lng:detail.lng,accuracy:detail.accuracy});});document.addEventListener("visibilitychange",function(){if(document.hidden)releaseMedia();});}
    window.TimeTraceEngine={registerPhoto:registerPhoto,openLibrary:openLibrary,checkRevisit:checkRevisit,_test:{proximity:proximity,radiusForAccuracy:radiusForAccuracy,combinedScore:combinedScore,edgeDescriptor:edgeDescriptor,REVISIT_DELAY_MS:REVISIT_DELAY_MS}};
    if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
